#!/usr/bin/env python3
"""Regenerates the navigation database and diffs it byte for byte against the capture.

Two separate stages, so a serialization bug is never mistaken for a simplification
bug:

  stage (a), always run    : reparses the structures of the capture, rebuilds them,
             and demands identity. Tests serialization only.
  stage (b), with --from-gpx: recomputes the fields derivable from the source GPX
             (bbox centre, extremes, coordinates, altitude) and compares them.

    ./tools/regen_route.py "assets/ambit3 pcap/route12km" \\
        --from-gpx "assets/ambit3 pcap/Gare-du-Nord-to-114-Av.-André-Morizet.gpx"
"""

import argparse
import re
import sys

import ambit_format as F
from ambit_pcap import FlashImage, messages, tails, write_packs

RTEPT = re.compile(r'<rtept\s+lat="([-\d.]+)"\s+lon="([-\d.]+)"\s*'
                   r'(?:/>|>(?:<ele>([-\d.]+)</ele>)?</rtept>)')
WPT = re.compile(r'<wpt\s+lat="([-\d.]+)"\s+lon="([-\d.]+)"\s*>(.*?)</wpt>', re.S)
TAG = re.compile(r"<(name|type)>(.*?)</\1>", re.S)
META_NAME = re.compile(r"<metadata>.*?<name>(.*?)</name>", re.S)


def read_gpx(path):
    """Export from the Suunto app: <metadata><name> carries the route name, the
    <wpt> carry the waypoints, the <rtept> the track."""
    raw = open(path, encoding="utf-8", errors="replace").read()
    points = [(float(lat), float(lon), float(ele) if ele else None)
              for lat, lon, ele in RTEPT.findall(raw)]
    waypoints = []
    for lat, lon, body in WPT.findall(raw):
        fields = dict(TAG.findall(body))
        waypoints.append((float(lat), float(lon),
                          fields.get("name", "").strip(), fields.get("type", "").strip()))
    name = META_NAME.search(raw)
    return (name.group(1).strip() if name else None), points, waypoints


def result(label, ok, detail=""):
    print(f"  {'OK   ' if ok else 'FAIL '} {label}{'   ' + detail if detail else ''}")
    return ok


def roundtrip(flash, msgs):
    print("== stage (a): reserialization of the capture's structures")
    ok = True
    header = F.RouteHeader.parse(flash.read(F.ROUTE_BASE, 32))
    m, p = header.route_count, header.point_count

    descriptors = [F.RouteDescriptor.parse(flash.read(F.ROUTE_DESC + 52 * i, 52))
                   for i in range(m)]
    points = [F.RoutePoint.parse(flash.read(F.ROUTE_POINTS + 12 * i, 12))
              for i in range(p)]
    wh = F.WaypointHeader.parse(flash.read(F.WAYPOINT_BASE, 6))
    waypoints = [F.WaypointDescriptor.parse(flash.read(F.WAYPOINT_DESC + 52 * i, 52))
                 for i in range(wh.count)]

    desc_blob = b"".join(d.build() for d in descriptors)
    point_blob = b"".join(q.build() for q in points)
    wpt_blob = b"".join(w.build() for w in waypoints)

    ok &= result("route descriptors", desc_blob == flash.read(F.ROUTE_DESC, 52 * m))
    ok &= result("point body", point_blob == flash.read(F.ROUTE_POINTS, 12 * p))
    ok &= result("waypoint descriptors",
                 wpt_blob == flash.read(F.WAYPOINT_DESC, 52 * wh.count))

    if m:
        rebuilt = F.RouteHeader(m, p, F.crc16_ccitt_false(desc_blob + point_blob)).build()
    else:
        rebuilt = F.ROUTE_HEADER_RESET
    ok &= result("route header (32 B, crc included)",
                 rebuilt == flash.read(F.ROUTE_BASE, 32))
    ok &= result("waypoint header (6 B, crc included)",
                 F.WaypointHeader.build_for(wpt_blob, wh.count)
                 == flash.read(F.WAYPOINT_BASE, 6))

    # The rebuilt image must yield the same closing hashes.
    rebuild = FlashImage()
    rebuild.write(F.ROUTE_BASE, rebuilt)
    rebuild.write(F.ROUTE_DESC, desc_blob)
    rebuild.write(F.ROUTE_POINTS, point_blob)
    rebuild.write(F.ROUTE_INDEX, flash.read(F.ROUTE_INDEX, 20 * m))
    rebuild.write(F.WAYPOINT_INDEX, flash.read(F.WAYPOINT_INDEX, 4 * wh.count))
    rebuild.write(F.WAYPOINT_BASE, F.WaypointHeader.build_for(wpt_blob, wh.count))
    rebuild.write(F.WAYPOINT_DESC, wpt_blob)
    for addr, _, want in tails(msgs):
        if addr in (F.ROUTE_BASE, F.WAYPOINT_BASE):
            name = F.REGIONS[addr][0]
            ok &= result(f"hash {name} from the rebuilt image",
                         F.region_hash(rebuild, addr) == want)
    return ok


def check_waypoints(flash, route_name, gpx_waypoints):
    """Only the <wpt> of type "Waypoint" become descriptors; the "Begin" and "End"
    auto-generated by the app are discarded. Verified on 3 captures (2, 9 and 11
    descriptors for 4, 11 and 4+11 <wpt>)."""
    wanted = [w for w in gpx_waypoints if w[3] == "Waypoint"]
    header = F.WaypointHeader.parse(flash.read(F.WAYPOINT_BASE, 6))
    written = [F.WaypointDescriptor.parse(flash.read(F.WAYPOINT_DESC + 52 * i, 52))
               for i in range(header.count)]
    # A capture may carry the waypoints of several routes: keep only the ones
    # attached to this one, by comparing the name as it is stored.
    short_route_name = F.decode_name(F.encode_name(route_name, "utf-8"))
    mine = [w for w in written if w.route_name == short_route_name]
    ok = result("count of waypoints of type Waypoint", len(wanted) == len(mine),
                f"GPX {len(wanted)} / capture {len(mine)}")
    if len(wanted) != len(mine):
        return False
    for (lat, lon, name, _), got in zip(wanted, mine):
        rebuilt = F.WaypointDescriptor(round(lat * 1e7), round(lon * 1e7), name,
                                       route_name, got.tail).build()
        ok &= result(f"descriptor {name[:24]!r}", rebuilt == got.build(),
                     "" if rebuilt == got.build() else
                     f"\n         computed {rebuilt.hex(' ')}"
                     f"\n         captured {got.build().hex(' ')}")
    return ok


def from_gpx(flash, gpx_path, route_index):
    name, gpx, gpx_waypoints = read_gpx(gpx_path)
    print(f"== stage (b): fields derived from the GPX  ({len(gpx)} points, "
          f"{len(gpx_waypoints)} wpt, "
          f"altitudes {'present' if gpx and gpx[0][2] is not None else 'absent'})")
    ok = True
    d = F.RouteDescriptor.parse(flash.read(F.ROUTE_DESC + 52 * route_index, 52))
    if not gpx or d.point_count == 0:
        return result("GPX and descriptor not empty", False)

    mid_lat, mid_lon = F.bbox_mid(gpx)
    ok &= result("bbox centre x 1e7", (mid_lat, mid_lon) == (d.mid_lat, d.mid_lon),
                 f"computed ({mid_lat}, {mid_lon}) / captured ({d.mid_lat}, {d.mid_lon})")

    if name:
        ok &= result("name truncated to 15 B in ISO-8859-15",
                     F.encode_name(name) == flash.read(F.ROUTE_DESC + 52 * route_index, 16),
                     f"GPX {name!r} -> {d.name!r}")

    # Extremes: the bbox of the full GPX must give the descriptor's max, which amounts
    # to saying the simplification keeps the extreme points.
    lats = [q[0] for q in gpx]
    lons = [q[1] for q in gpx]
    max_x = F.relative_xy(mid_lat, mid_lon, mid_lat / 1e7, max(lons))[0]
    max_y = F.relative_xy(mid_lat, mid_lon, max(lats), mid_lon / 1e7)[1]
    ok &= result("max_x", max_x == d.max_x, f"computed {max_x} / captured {d.max_x}")
    ok &= result("max_y", max_y == d.max_y, f"computed {max_y} / captured {d.max_y}")

    points = [F.RoutePoint.parse(flash.read(F.ROUTE_POINTS + 12 * i, 12))
              for i in range(d.start_index, d.start_index + d.point_count)]
    inverted = [F.inverse_xy(d.mid_lat, d.mid_lon, q.x, q.y) for q in points]

    # The test that counts: identify the source GPX point of every record, then demand
    # that the projection yields exactly the stored integers.
    sources = []
    for la, lo in inverted:
        sources.append(min(gpx, key=lambda g: F.haversine_m(la, lo, g[0], g[1])))
    bad = sum(1 for g, q in zip(sources, points)
              if F.relative_xy(d.mid_lat, d.mid_lon, g[0], g[1]) != (q.x, q.y))
    ok &= result("x/y recomputed from the source GPX point", bad == 0,
                 f"{len(points) - bad}/{len(points)} exact")

    errs = sorted(F.haversine_m(la, lo, g[0], g[1])
                  for (la, lo), g in zip(inverted, sources))
    ok &= result("every stored point lands on a GPX point", errs[-1] < 2.0,
                 f"median {errs[len(errs) // 2]:.2f} m, max {errs[-1]:.2f} m")

    if all(g[2] is not None for g in sources):
        # Several GPX points can project onto the same (x,y) pair: accept the
        # altitude if it matches any one of them.
        colocated = {}
        for la, lo, ele in gpx:
            colocated.setdefault(F.relative_xy(d.mid_lat, d.mid_lon, la, lo), []).append(ele)
        exact = sum(1 for q in points
                    if any(int(e) == q.altitude for e in colocated.get((q.x, q.y), [])))
        ok &= result("altitude = truncation of <ele>", exact == len(points),
                     f"{exact}/{len(points)} exact")

    # rel_distance depends on the exact sequence of source points, which is only
    # approximately reconstructed here: informative until milestone 3, where the
    # simplification will produce the sequence directly.
    computed = F.relative_distances([(g[0], g[1]) for g in sources])
    hits = sum(1 for a, q in zip(computed, points) if a == q.rel_distance)
    print(f"  info  rel_distance recomputed exact on {hits}/{len(points)} points")

    # distance: a value supplied by the app (totalDistance), not exactly rederivable.
    # The best local estimate is the full GPX.
    total, _ = F.cumulative_distance_m([(g[0], g[1]) for g in gpx])
    print(f"  info  captured distance {d.distance} m; cumulative of the full GPX "
          f"{total:.0f} m ({abs(total - d.distance) / d.distance * 100:.2f} %)  -> residual")

    alt = [q.altitude for q in points if q.altitude != F.ALTITUDE_NONE]
    if alt:
        up = sum(max(0, b - a) for a, b in zip(alt, alt[1:]))
        down = sum(max(0, a - b) for a, b in zip(alt, alt[1:]))
        full = [q[2] for q in gpx if q[2] is not None]
        up_full = sum(max(0, b - a) for a, b in zip(full, full[1:]))
        down_full = sum(max(0, a - b) for a, b in zip(full, full[1:]))
        print(f"  info  captured ascent/descent ({d.ascent}, {d.descent}); "
              f"stored altitudes ({up}, {down}); "
              f"full GPX ({up_full:.0f}, {down_full:.0f})  -> residual 6")

    if name:
        ok &= check_waypoints(flash, name, gpx_waypoints)
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("capture")
    ap.add_argument("--from-gpx", metavar="GPX")
    ap.add_argument("--route", type=int, default=0,
                    help="index of the descriptor to compare")
    args = ap.parse_args()

    msgs = messages(args.capture)
    flash = FlashImage(write_packs(msgs))
    print(f"### {args.capture}")
    ok = roundtrip(flash, msgs)
    if args.from_gpx:
        print()
        ok &= from_gpx(flash, args.from_gpx, args.route)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
